### PR TITLE
TIS-382: Added delay

### PR DESCRIPTION
**Pull request by wkaminsk**

### CODE REVIEW

**Review by Daniel-Shai — APPROVED** [review]

**Review by Daniel-Shai — APPROVED** [review]
[TIS-382](https://riskified.atlassian.net/browse/TIS-382)

**Comment by Daniel-Shai** [comment]
[TIS-382]

**Review by Daniel-Shai — APPROVED** [review]
[TIS-382](https://riskified.atlassian.net/browse/TIS-382)

**Review by Daniel-Shai — APPROVED** [review]

**Review by Daniel-Shai — APPROVED** [review]
[TIS-382](https://riskified.atlassian.net/browse/TIS-382)

**Comment by Daniel-Shai** [comment]
[TIS-382](https://riskified.atlassian.net/browse/TIS-382)

**Review by Daniel-Shai — APPROVED** [review]
TIS-382 Approved

**Review by Daniel-Shai — APPROVED** [review]

**Review by mooseriskified — APPROVED** [review]

**Review by dormini — APPROVED** [review]

**Review by dormini — APPROVED** [review]

**Review by gkid — APPROVED** [review]
Team is waiting for approval from security to get Write permissions on the repo.
I'm approving for this time (Mustafa has already approved as well)

**Pull request merged**
